"""Add AI investigation fields to RecoveryCase

Revision ID: 79f19d2b77d3
Revises: 6b233d679ee0
Create Date: 2026-09-04 22:59:39.497075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f19d2b77d3'
down_revision: Union[str, Sequence[str], None] = '6b233d679ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('ai_diagnosis', sa.String(length=100), nullable=True))
    op.add_column('recovery_cases', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('recovery_cases', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('recovery_cases', sa.Column('ai_evidence', sa.JSON(), nullable=True))
    op.add_column('recovery_cases', sa.Column('ai_recommended_action', sa.String(length=50), nullable=True))
    op.add_column('recovery_cases', sa.Column('policy_result', sa.String(length=20), nullable=True))
    op.add_column('recovery_cases', sa.Column('final_action', sa.String(length=50), nullable=True))
    op.add_column('recovery_cases', sa.Column('escalation_required', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'escalation_required')
    op.drop_column('recovery_cases', 'final_action')
    op.drop_column('recovery_cases', 'policy_result')
    op.drop_column('recovery_cases', 'ai_recommended_action')
    op.drop_column('recovery_cases', 'ai_evidence')
    op.drop_column('recovery_cases', 'ai_summary')
    op.drop_column('recovery_cases', 'ai_confidence')
    op.drop_column('recovery_cases', 'ai_diagnosis')
    # ### end Alembic commands ###
